server:
  port: 8090

spring:
  application:
    name: mcp-service
  data:
    mongodb:
      uri: mongodb://amor:123456@localhost:27017/amor
  ai:
    mcp:
      server:
        name: ww-mcp-server
        version: 1.0.0
        type: sync
        sse-message-endpoint: /mcp/message
        sse-endpoint: /sse

taskflow:
  auth: Bearer bcDdKSQri6elHgB--rGLNHh8B2ivw-J-ZJLwDPZxGMoQEeTUSUQmDwcWKjr_bWzeH3N_pqHkvCzlCNlPKMaB67wOIuSpaDb3nKDJusS2vi_3Tdq5cKJarcLokl2t2-XX
