server:
  port: 8081

vaadin:
  launch-browser: true

spring:
  application:
    name: ww-ai
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: sk-230bfda20028442fa97583fe9bbbaf52
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
    mcp:
      client:
        name: ww-mcp-client
        type: sync
        toolcallback:
          enabled: true
        sse:
          connections:
            weather:
              url: http://localhost:8090
