server:
  port: 8081

vaadin:
  launch-browser: true

spring:
  application:
    name: ww-ai
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  data:
    mongodb:
      uri: mongodb://amor:123456@localhost:27017/amor
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: sk-c65e753a45d140f991a80f42c2929b01
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
    playground:
      chat:
        systemPrompt: 你是一位某系统助理，你需要遵循一下规则：1:当用户需要获取系统验证码时，调用获取系统验证码tool时，你的请求tool参数应该时应该是标准的UUID.
        models:
          - deepseek-chat
          - deepseek-reasoner
    mcp:
      client:
        name: ww-mcp-client
        type: sync
        toolcallback:
          enabled: true
        sse:
          connections:
            #amor MCP服务
            amor:
              url: http://localhost:8090


logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.ai.chat: DEBUG